# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WaitingRoom.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(960, 540)
        self.graphicsView = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView.setGeometry(QtCore.QRect(20, 70, 441, 41))
        self.graphicsView.setObjectName("graphicsView")
        self.graphicsView_3 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_3.setGeometry(QtCore.QRect(20, 130, 441, 41))
        self.graphicsView_3.setObjectName("graphicsView_3")
        self.graphicsView_4 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_4.setGeometry(QtCore.QRect(20, 190, 441, 41))
        self.graphicsView_4.setObjectName("graphicsView_4")
        self.graphicsView_5 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_5.setGeometry(QtCore.QRect(20, 250, 441, 41))
        self.graphicsView_5.setObjectName("graphicsView_5")
        self.graphicsView_6 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_6.setGeometry(QtCore.QRect(20, 490, 441, 41))
        self.graphicsView_6.setObjectName("graphicsView_6")
        self.graphicsView_7 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_7.setGeometry(QtCore.QRect(20, 310, 441, 41))
        self.graphicsView_7.setObjectName("graphicsView_7")
        self.graphicsView_8 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_8.setGeometry(QtCore.QRect(20, 370, 441, 41))
        self.graphicsView_8.setObjectName("graphicsView_8")
        self.graphicsView_9 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_9.setGeometry(QtCore.QRect(20, 430, 441, 41))
        self.graphicsView_9.setObjectName("graphicsView_9")
        self.graphicsView_10 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_10.setGeometry(QtCore.QRect(490, 370, 441, 41))
        self.graphicsView_10.setObjectName("graphicsView_10")
        self.graphicsView_11 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_11.setGeometry(QtCore.QRect(490, 250, 441, 41))
        self.graphicsView_11.setObjectName("graphicsView_11")
        self.graphicsView_2 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_2.setGeometry(QtCore.QRect(490, 70, 441, 41))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.graphicsView_12 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_12.setGeometry(QtCore.QRect(490, 310, 441, 41))
        self.graphicsView_12.setObjectName("graphicsView_12")
        self.graphicsView_13 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_13.setGeometry(QtCore.QRect(490, 430, 441, 41))
        self.graphicsView_13.setObjectName("graphicsView_13")
        self.graphicsView_14 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_14.setGeometry(QtCore.QRect(490, 130, 441, 41))
        self.graphicsView_14.setObjectName("graphicsView_14")
        self.graphicsView_15 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_15.setGeometry(QtCore.QRect(490, 190, 441, 41))
        self.graphicsView_15.setObjectName("graphicsView_15")
        self.graphicsView_16 = QtWidgets.QGraphicsView(Dialog)
        self.graphicsView_16.setGeometry(QtCore.QRect(490, 490, 441, 41))
        self.graphicsView_16.setObjectName("graphicsView_16")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(410, 20, 131, 31))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(360, 80, 81, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(360, 140, 81, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(360, 200, 81, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(360, 260, 81, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(360, 500, 81, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(360, 440, 81, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(360, 320, 81, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(360, 380, 81, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(830, 320, 81, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(Dialog)
        self.pushButton_10.setGeometry(QtCore.QRect(830, 260, 81, 21))
        self.pushButton_10.setObjectName("pushButton_10")
        self.pushButton_11 = QtWidgets.QPushButton(Dialog)
        self.pushButton_11.setGeometry(QtCore.QRect(830, 200, 81, 21))
        self.pushButton_11.setObjectName("pushButton_11")
        self.pushButton_12 = QtWidgets.QPushButton(Dialog)
        self.pushButton_12.setGeometry(QtCore.QRect(830, 440, 81, 21))
        self.pushButton_12.setObjectName("pushButton_12")
        self.pushButton_13 = QtWidgets.QPushButton(Dialog)
        self.pushButton_13.setGeometry(QtCore.QRect(830, 80, 81, 21))
        self.pushButton_13.setObjectName("pushButton_13")
        self.pushButton_14 = QtWidgets.QPushButton(Dialog)
        self.pushButton_14.setGeometry(QtCore.QRect(830, 500, 81, 21))
        self.pushButton_14.setObjectName("pushButton_14")
        self.pushButton_15 = QtWidgets.QPushButton(Dialog)
        self.pushButton_15.setGeometry(QtCore.QRect(830, 140, 81, 21))
        self.pushButton_15.setObjectName("pushButton_15")
        self.pushButton_16 = QtWidgets.QPushButton(Dialog)
        self.pushButton_16.setGeometry(QtCore.QRect(830, 380, 81, 21))
        self.pushButton_16.setObjectName("pushButton_16")
        self.lcdNumber = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber.setGeometry(QtCore.QRect(290, 80, 64, 23))
        self.lcdNumber.setObjectName("lcdNumber")
        self.lcdNumber_2 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_2.setGeometry(QtCore.QRect(290, 140, 64, 23))
        self.lcdNumber_2.setObjectName("lcdNumber_2")
        self.lcdNumber_3 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_3.setGeometry(QtCore.QRect(290, 260, 64, 23))
        self.lcdNumber_3.setObjectName("lcdNumber_3")
        self.lcdNumber_4 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_4.setGeometry(QtCore.QRect(290, 200, 64, 23))
        self.lcdNumber_4.setObjectName("lcdNumber_4")
        self.lcdNumber_5 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_5.setGeometry(QtCore.QRect(290, 380, 64, 23))
        self.lcdNumber_5.setObjectName("lcdNumber_5")
        self.lcdNumber_6 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_6.setGeometry(QtCore.QRect(290, 320, 64, 23))
        self.lcdNumber_6.setObjectName("lcdNumber_6")
        self.lcdNumber_7 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_7.setGeometry(QtCore.QRect(290, 500, 64, 23))
        self.lcdNumber_7.setObjectName("lcdNumber_7")
        self.lcdNumber_8 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_8.setGeometry(QtCore.QRect(290, 440, 64, 23))
        self.lcdNumber_8.setObjectName("lcdNumber_8")
        self.lcdNumber_9 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_9.setGeometry(QtCore.QRect(750, 440, 64, 23))
        self.lcdNumber_9.setObjectName("lcdNumber_9")
        self.lcdNumber_10 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_10.setGeometry(QtCore.QRect(750, 140, 64, 23))
        self.lcdNumber_10.setObjectName("lcdNumber_10")
        self.lcdNumber_11 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_11.setGeometry(QtCore.QRect(750, 380, 64, 23))
        self.lcdNumber_11.setObjectName("lcdNumber_11")
        self.lcdNumber_12 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_12.setGeometry(QtCore.QRect(750, 260, 64, 23))
        self.lcdNumber_12.setObjectName("lcdNumber_12")
        self.lcdNumber_13 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_13.setGeometry(QtCore.QRect(750, 320, 64, 23))
        self.lcdNumber_13.setObjectName("lcdNumber_13")
        self.lcdNumber_14 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_14.setGeometry(QtCore.QRect(750, 80, 64, 23))
        self.lcdNumber_14.setObjectName("lcdNumber_14")
        self.lcdNumber_15 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_15.setGeometry(QtCore.QRect(750, 200, 64, 23))
        self.lcdNumber_15.setObjectName("lcdNumber_15")
        self.lcdNumber_16 = QtWidgets.QLCDNumber(Dialog)
        self.lcdNumber_16.setGeometry(QtCore.QRect(750, 500, 64, 23))
        self.lcdNumber_16.setObjectName("lcdNumber_16")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "<html><head/><body><p align=\"center\"><span style=\" font-size:18pt;\">대기실</span></p></body></html>"))
        self.pushButton.setText(_translate("Dialog", "입장하기"))
        self.pushButton_2.setText(_translate("Dialog", "입장하기"))
        self.pushButton_3.setText(_translate("Dialog", "입장하기"))
        self.pushButton_4.setText(_translate("Dialog", "입장하기"))
        self.pushButton_5.setText(_translate("Dialog", "입장하기"))
        self.pushButton_6.setText(_translate("Dialog", "입장하기"))
        self.pushButton_7.setText(_translate("Dialog", "입장하기"))
        self.pushButton_8.setText(_translate("Dialog", "입장하기"))
        self.pushButton_9.setText(_translate("Dialog", "입장하기"))
        self.pushButton_10.setText(_translate("Dialog", "입장하기"))
        self.pushButton_11.setText(_translate("Dialog", "입장하기"))
        self.pushButton_12.setText(_translate("Dialog", "입장하기"))
        self.pushButton_13.setText(_translate("Dialog", "입장하기"))
        self.pushButton_14.setText(_translate("Dialog", "입장하기"))
        self.pushButton_15.setText(_translate("Dialog", "입장하기"))
        self.pushButton_16.setText(_translate("Dialog", "입장하기"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())

